main.py
from flask import Flask
from flask_bootstrap import Bootstrap

import views

app = Flask(__name__)
app.config['SECRET_KEY'] = 'Yet another secret key'

app.register_blueprint(views.hello)
Bootstrap(app)

views.py
from flask import (
    Blueprint, request, redirect, render_template, url_for, flash)
import requests
import html

from random import randint

from model import MyForm

hello = Blueprint("hello", __name__)


favourite_movies_list = []


@hello.route('/', methods=['GET', 'POST'])
def index():
    form = MyForm(csrf_enabled=False)
    page = 1
    if request.method == "POST":
        t = form.search_bar.data  # t==title
        return redirect(url_for(
            'hello.search_result',
            page=page,
            title=t)
            )
    return render_template(
                        'home.html',
                        form=form,
                        favourite_movies=favourite_movies_list)


@hello.route("/info/<movie_title>", methods=['GET', 'POST'])
def movie_page(movie_title):
    error = ''
    movie_data = requests.get(
            url=f'http://www.omdbapi.com/?apikey=22a96d18&plot=full&t={movie_title}'
                ).json()
    if request.method == "POST":
        if request.form["fav_toggle"] == 'add':
            for movie in favourite_movies_list:
                if movie_data['title'] == movie:
                    error = "Movie already exist in favourites"
                    flash(error, "error")
                    return redirect(url_for(
                        'hello.movie_page',
                        movie_title=movie_title))
            favourite_movies_list.append(movie_data)
            flash('Movie added to favourite', 'success')
        elif request.form["fav_toggle"] == 'remove':
            favourite_movies_list.remove(movie_data)
            flash("Removed from favourites", "success")
        return redirect(url_for('hello.movie_page', movie_title=movie_title))
    return render_template('movie_info.html', movie_data=movie_data)


@hello.route("/random")
def find_random_movie():
    id = randint(1111111, 9999999)
    imdb_id = f"tt{id}"
    data = requests.get(
                url=f'http://www.omdbapi.com/?apikey=22a96d18&plot=full&i={imdb_id}'
                ).json()
    if 'Error' in data:
        return redirect(url_for('hello.index'))
    movie_data = {
            'title': data['Title'],
            'year': data['Year'],
            'plot': data['Plot'],
            'poster': data['Poster'],
            }
    return redirect(
            url_for('hello.movie_page', movie_title=movie_data['title']))


@hello.route("/search/<title>", defaults={'page': 1})
@hello.route("/search/<title>/<int:page>")
def search_result(page, title):
    empty_icon = html.escape('∅', quote=False)
    try:
        result = requests.get(
                url=f'http://www.omdbapi.com/?apikey=22a96d18&s={title}&page={page}'
                ).json()
        result_list = result['Search']
    except KeyError:
        flash("Movie Title not found", "error")
        return redirect(url_for("hello.index"))
    total_results = int(result['totalResults'])
    total_page = round(total_results/10)
    return render_template(
            'search_page.html',
            result=result_list,
            page=page,
            total_page=total_page,
            empty=empty_icon,
            title=title,
           )

templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} FindMyMovies {% endblock %}



{% block styles %}
{{ super() }}
<link rel="stylesheet" 
      href="{{ url_for('static', filename='css/style.css') }}">
{% endblock %}

{% block navbar %}
<nav class = "navbar navbar-inverse navbar-fixed-top" role = "navigation">
  <div class="container-fluid">
   <div class = "navbar-header">
      <button type = "button" class = "navbar-toggle" 
         data-toggle = "collapse" data-target = "#example-navbar-collapse">
         <span class = "sr-only">Toggle navigation</span>
         <span class = "icon-bar"></span>
         <span class = "icon-bar"></span>
         <span class = "icon-bar"></span>
      </button>
      <a class = "navbar-brand" href = "/">FindMyMovies</a>
   </div>
   <div class = "collapse navbar-collapse" id = "example-navbar-collapse">
      <ul class = "nav navbar-nav">
         <li class = "active"><a href = "/">Home</a></li>
         <li><a href = "{{ url_for('hello.find_random_movie') }}">Random Movie</a></li>
      </ul>
   </div>
  </div>
</nav>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      {% set message_class = 'alert-success' %}
      {% if category == 'error' %}
        {% set message_class = 'alert-danger'%}
      {% endif %}
      <div class="alert {{ message_class }}
        alert-dismissable fade in">
        {{ message }}
        <button type="button" class="close"
          aria-label="Close" aria-hidden="true" data-dismiss="alert">
          &times;
        </button>
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}
<div class="top-pad" style="margin: 10px;">
  <form method='POST' action='/'>
    {{ wtf.quick_form(form) }}
  </form>
</div>
<div class="container">
  <h2>Favourites</h2>
  <div class="well">
    {% for movie in favourite_movies %}
    <div class="container fav-card">
      <div class="card-body">
        <h5 class="card-title">{{ movie['Title'] }}</h5>
        <p class="card-text">{{ movie['Year'] }}</p>
        <form method="POST">
          <a type='button' role="button" class="btn btn-info btn-sm fav-btn"
                           href="{{ url_for('hello.movie_page', movie_title=movie['Title']) }}">
            Movie Info</a>
        </form>
      </div>
      <img src="{{ movie['Poster'] }}" class="card-img"></img>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/movie_info.html
{% extends "base.html" %}
{% block content %}
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      {% set message_class = 'alert-success' %}
      {% if category == 'error' %}
        {% set message_class = 'alert-danger'%}
      {% endif %}
      <div class="alert {{ message_class }} 
        alert-dismissable fade in">
        {{ message }}
        <button type="button" class="close" 
          aria-label="Close" aria-hidden="true" data-dismiss="alert">
          &times;
        </button>
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}
<div class="container">
  <div class="well">
    <div class="container" style="display: flex; justify-content: center;">
      <img class="img-rounded "  
      src="{{ movie_data['Poster'] }}" alt="Poster">
    </div>
    <div class='cointainer'>
      <h2 class="card-text">{{ movie_data['Title'] }}</h2>
      <p class="card-text">Date Released: {{ movie_data['Released'] }}</p>
      <p class"card-text">Runtime: {{ movie_data['Runtime'] }}</p>
      <p class="card-text">Actors: {{ movie_data['Actors'] }}</p>
      <p>Genre: {{ movie_data['Genre'] }}</p>
      <p class="card-text">{{ movie_data['Plot'] }}</p>
      <span>Ratings:</span>
      <div class="list-inline">
      {% for rating in movie_data['Ratings'] %}
        <li class="card-text">
          {{ rating['Source'] }}: {{ rating['Value'] }}
        </li>
      {% endfor %}
      </div>
    </div>
    <div class='container'>
      <form method="POST">
        <button type="submit" class="btn btn-primary fav-btn" 
          name="fav_toggle" value="add" {{ in_fav }}>Add to Favourites</button>
        <button type="submit" class="btn 
          btn-danger fav-btn" name="fav_toggle" value="remove" >Remove from Favourites</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/search_page.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
  <h1>Search Result:</h1>
</div>
<div class="container-fluid">
{% for movie in result %}
  <div class="well movie-card container">
      <div class="col">
        <h2>{{ movie['Title'] }}</h2>
        <p>{{ movie['Year'] }}</p>
        <a type='button' role="button" 
                         class="btn btn-info btn-sm fav-btn"
                         href="{{ url_for('hello.movie_page', movie_title=movie['Title']) }}">Movie Info</a>
      </div>
      <div class="col image-card img-thumbnail">
        <img src="{{ movie['Poster'] }}" alt="None">
      </div>
  </div>
{% endfor %}
</div>
<div>
  {# If statement to check if the pagination bar #}
  {# is at the beginning or end #}
    {% if page == 1 %}
      {% set disabled='disabled' %}
      {% set first_page_url='#' %}
      {% set first_placeholder = empty %}
    {% else %}
      {% set disabled = '' %}
      {% set first_page_url = url_for('hello.search_result', page=page-1, title=title) %}
      {% set first_placeholder = page-1 %}
    {% endif %}
    {% if page == total_page %}
      {% set disabled='disabled' %}
      {% set last_page_url='#' %}
      {% set last_placeholder = empty %}
    {% else %}
      {% set disabled = '' %}
      {% set last_page_url = url_for('hello.search_result', page=page+1, title=title) %}
      {% set last_placeholder = page+1 %}
    {% endif %}
  <ul class="pagination" style="display: flex; justify-content: center">
    <li class="page-item">
      <a class="page-link" href="{{ first_page_url }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    <li class="page-item "><a class="page-link {{ disabled }}" href="{{ first_page_url }}">{{ first_placeholder }}</a></li>
    <li class="page-item"><a class="page-link active" href="{{ url_for('hello.search_result', page=page, title=title) }}">{{ page }}</a></li>
    <li class="page-item"><a class="page-link {{ disabled }}" href="{{ last_page_url }}">{{ last_placeholder }}</a></li>
    <li class="page-item">
      <a class="page-link" href="{{ last_page_url }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
  </ul>
</div>  
{% endblock %}